# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FanbookCover' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'GBInfiniteScrollView'
 
  # Pods for FanbookCover

  target 'FanbookCoverTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
